### ISSUE TITLE
Create quality gate for repository

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/agent-python-pytest#40]
**Goal:** 

Automatic checks for new pull requests.

**Tasks:**

- [ ] Add tests folder with several unit tests with mock class
- [ ] Add test runner script which prepares environment and runs all tests
- [ ] Update travis.yml

**Tests:**

- Create launch test: check whether new launch created or not
- Log Test test: check whether current test is logged in report portal
- Log message test: check whether log contains some custom log message

**Environment preparation:**

- download reportportal docker-compose file
- docker-compose up -d
- install requirements.txt (reportportal client, etc.)
- run tests with reportportal integration

**Comment by ailjushkin** [comment]
@avarabyeu Could you please review description and add your thoughts on this topic?

**Comment by krasoffski** [comment]
Hi @ailjushkin,

#### Here is my thoughts. 
Having real RP portal is big problem due to big resource consumption and services start up.
I would recommend to create `TestService` or `TestClient` Python class which do not send real request to Report Portal but collects calls which can be then checked (simple mock class). 
It is easy to implement and integrate to testing. Also, there are some cons related to same checks which performed each time.

**Comment by ailjushkin** [comment]
@krasoffski Thanks, I've edited issue description

**Comment by DzmitryHumianiuk** [comment]
@ailjushkin we gonna set up demo instance pretty soon.
so demo api can be used as endpoint for tests

**Comment by HardNorth** [comment]
Done with Github Actions
